#数据库连接
spring:

    datasource:
        url: jdbc:mysql://localhost:3306/playground?serverTimezone=UTC
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver

    mybatis:
        typeAliasesPackage: com.park.pojo
        mapperLocations: classpath:mappers/*.xml
    mvc:
        view:
          prefix: templates/
          suffix: .html
#服务器端口
server:
  port: 8080
  